### ISSUE TITLE
Text Korrekturen

### ISSUE THREAD

**Issue by DaMnSiCc** [poLLi/DM_Tools#5]
Das Wort mit dem Fehler setze ich in Anführungszeichen
**Occupation:**
"Constuction" Worker -> Construction"

Repair Man:
Spawn with casual "attiere" ->attire

Chef: (Text wenn man mit dem Mauszeiger über der occupation hovert)
You have always liked to spend time in the "kitches" -> kitchen

Fire Fighter:
(hover text) sprung up during the "outbreake" -> outbreak

**Character Data:**

"Itelligence" -> Intelligence

**Perk Selection:**

CPR Training: bring people out of "unconsciusness" -> unconciousness

Astronomer: when pressing the HUD "promt" key -> prompt

Observant: with the HUD "promt" active -> prompt

Herbalist: Allows you to "easy" identify -> easily

Peanut Allergy: Triggers a "servere" allergic reaction [...] Spawn with "on" epi-pen -> severe, one

Awful Cook: "Reveive" a -25 penalty -> Receive

Green Thumb: Gain a +25 bonus to "Farmin" -> Farming

Gearhead: You "sepend" a lot of time -> spend

Volunteer Firefighter: when you were "yunger" -> younger

**Comment by poLLi** [comment]
will be fixed with upcoming localization feature

**Comment by poLLi** [comment]
**Fixed:** commit 5377294
